[default]
dynaconf_include = ["app/config/*.toml"]

### Deafult configurations
APP_NAME=''
SECRET_KEY=''
APP_URL='http://localhost:5000/'

#### Database
DB_CONNECTION='sqlite'
DB_HOST='/resources/database.db'
DB_PORT=''
DB_NAME=''
DB_USERNAME=''
DB_PASSWORD=''

### Mail 
MAIL_MAILER=''
MAIL_HOST=''
MAIL_PORT='2525'
MAIL_USERNAME='null'
MAIL_PASSWORD='null'
MAIL_ENCRYPTION='null'
MAIL_FROM_ADDRESS='null'
MAIL_FROM_NAME=''
